= How to improve your daily standup meetings
Aleksand Erokhin <https://aerokhin.com>
:stylesdir: ../stylesheets
:stylesheet: adoc-github.css
:imagedir: ../images
:icons: font
:favicon: {imagedir}/lightbulb.png

What complains about daily standup meetings have you heard? "They are useless", "they take time I could be doing some real work", "I just tell my status and sit there for another half an our"?

That's how any developer feels sometimes. That can happen when your scum master or team lead simply follows agile rituals without any idea behind it. But even if they are putting an effort into it - a daily might still feel off.

Here are some of the approaches we use successfully in our team in order to make daily standup meetings more meaningful.

== 1. Make the attendance optional

In order to make teammates more involved, you need to make daily attendance optional. This sounds counterintuitive, but bear with me.

By making it optional, you are lifting the burden of inevitable waste of time that haunts developer. A developer now knows that he is not required to interrupt his flow in order to participate. If everything is going well for him - he can just happily code away. And for a team leader a ticket tracking system should be enough to track the progress.

On the other had - in case a team member has an impediment, he'll be there to share and seek for assistance. Or in case he's done an amazing job closing some tasks - he'll also join in order to announce such great news. In any case - you'll get an involved participant and will not interrupt the flow of others, who won't bring anything to the meeting this time except their frustration they had to interrupt their work.

== 2. Shuffle the order

Daily can easily become a routine. You know the order, in which everyone reports their status. You know I'll go next, you do your report and zone out, never listening to whatever someone has to say next. Have you ever came back to a person with a question to get: "Sorry, was that questions for me? Could you please repeat that." in response?

Two team members might be dealing with the same exact issue, but they'll never know, because they don't listen. When you know the drill - you can get distracted easily, because you don't have to pay attention.

But if order is different all the time - you have to follow and stay alerted. Once things are not scripted anymore, they require more involvement from your side. You don't know when your turn comes, so you have to listen now. It's also harder to zone out right after, so you stay alerted for some short period of time, that is enough to pay attention to other team members.

== 3. Timebox the meeting, but allow prolongation in a smaller round

Daily meeting should be carefully timeboxed. You don't usually want it to go over an half an hour (presuming team size of 12 people or so). But it doesn't mean that you have to interrupt a team member describing his issue just to move along. That might very well be the most frustrating thing: having to explain something when no one cares and get interrupted.

Good moderation approach would be - let a person describe his problem deep enough to understand who could help. Let others ask questions. Two or three minutes should be enough to get an idea about a problems realms and assign people who should be involved in order to resolve the impediment. As soon as it done - you can move along and stay in the call in a smaller round for more detailed discussion.

==  4. Use time in the end for team announcements

Daily is a great sync point. In case you have any team-wide announcement or question - it's a good idea to have it at the end of the meeting, when everyone is through with the status update. This way you bring additional value to the meeting and probably saving some time you'd need for sync up later on.

You can also use this time for announcements from other team members or for a small talk. After all it's still hard for some of us to switch to full remote work. Chit-chat after the daily could somewhat substitute a coffee break and help your colleges to recharge a bit.

Making this meeting less formal in that way might add value and make people to look forward to it.