= How to setup your asciidoc blog
Aleksand Erokhin <https://aerokhin.com>
:stylesdir: ../stylesheets
:stylesheet: adoc-github.css
:imagedir: ../images
:icons: font

-- beauty in simplicity

My fist ever blog posts were published on https://medium.com/[medium]. It was fine in the beginning, but soon I started to get annoyed by certain things there. Like there is no way to include a code block on a page. You have to create a bunch of https://docs.github.com/en/github/writing-on-github/editing-and-sharing-content-with-gists/creating-gists[gists] and link them. You can't backup or export your stories, your replies are also stories, you can't personalize your posts much. And paywall they have there is stupid.

So I've switched to https://wordpress.org/download/[wordpress] hosted in https://aws.amazon.com/[aws]. Which was also fine for a while. But eventually it felt like it has lots of features I don't need (like user registration and comments which are mostly used by spammers) and lacks features I need (simple backups and tracking changes in a version controll'y style).

That's when I decided to run a blog in asciidoc! That was a perfect fit for me. I've seen it a couple of times across the internet but has never considered to do a setup by myself until now.

In fact, you are reading this post in my new asciiblog.

== What is asciidoc

https://asciidoc.org/[AsciiDoc] is a text document format for writing notes, documentation, articles, books, ebooks, slideshows, web pages, man pages and blogs. AsciiDoc files can be translated to many formats including HTML, PDF, EPUB, man page.

Or to put it another way - asciidoc is a markup language that could be used to generate all sorts of static pages.

For example you just open up a plain text file with .adoc extension and write the following:

[source]
----
[NOTE]
====
Here is why I like asciidoc:

* text based;
* generates lightweight HTML5 pages;
* supports styling and customization.
====
----

Put it through asciidoc processor and receive the following render:

[NOTE]
====
Here is why I like asciidoc:

* text based;
* generates lightweight HTML5 pages;
* supports styling and customization.
====

Pretty cool! It has a reach set of capabilities, so if you are interested already, check out the https://docs.asciidoctor.org/asciidoc/latest/[markup documentation].

== Setup

=== Problems to solve

So I've picked a markup language. But I have some other problems to solve before I can actually post my markup files.

Fist, they have to be stored somewhere. Ideally - not locally. Because in that case loosing your local copy would mean loosing all your posts.

I could store it somewhere in the cloud, but since my posts are now just plain text files, I can use a cvs like https://github.com/[github]. It will host my files, make it accessible from anywhere and provide version control for them to easily track changes.

First one down.

Second, I need to render html pages from adoc files. That is an easy one. https://asciidoctor.org/[Asciidoctor] does just that and could be installed on any operating system.

Another down.

Last but not least, I need to serve my pages. Any web server could handle such an easy task. I picked nginx because I had some experience with it already.

Last one down!

=== Tools and technologies used

My current setup is the following.

I have Ubuntu 20.04 running on https://aws.amazon.com/ec2/?ec2-whats-new.sort-by=item.additionalFields.postDateTime&ec2-whats-new.sort-order=desc[aws ec2 instance]. It has https://nginx.org/[nginx] installed with https://certbot.eff.org/[certbot] used to acquire a Let's encrypt certificate.

My sources for the blog are located in https://github.com/commandercool/asciiblog[github public repository].

And finally I have https://asciidoctor.org/[aciidoctor] installed on my local machine to render these sources into some neat html pages.

=== Posting to the blog

When I have an idea for a new blog post - I start writing it in plain text in one of new `.adoc` files in the posts folder. I check in my changes to track progress and render the page locally from time to time to see what I am getting so far.

As soon as I feel that it's ready to be posted - I render the page locally and run `rsync` command in order to synchronize my local render with the one I have in AWS.